# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  devportal-aws

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  OpenSearchURL:
    Type: String
  PostgresURL:
    Type: String
  EnvironmentType:
    Description: Environment Type
    Default: dev
    Type: String
    AllowedValues: [dev, prod]
    ConstraintDescription: Must specify 'dev' or 'prod'

Conditions:
  IsProd: !Equals [!Ref EnvironmentType, prod]
  IsDev: !Equals [!Ref EnvironmentType, dev]

Globals:
  Function:
    Timeout: 60
    MemorySize: 128
    Environment:
      Variables:
        ES_URL: !Ref OpenSearchURL
        PG_URL: !Ref PostgresURL
        ENVIRONMENT: !Ref EnvironmentType

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL
      Models:
        FeedbackModel:
          type: object
          properties:
            vote:
              type: string
            message:
              type: string
            created_at:
              type: string
            referrer:
              type: string

  SearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/search.searchHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 60
      Description: A simple GET function to fetch all results from a search query
      Events:
        Search:
          Type: Api
          Properties:
            Path: /search
            Method: get
            RestApiId:
              Ref: RestApi

  CreateFeedbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/create-feedback.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 60
      Description: A simple POST function to submit a feedback
      Events:
        Search:
          Type: Api
          Properties:
            Path: /createFeedback
            Method: post
            RestApiId:
              Ref: RestApi
            RequestModel:
              Model: FeedbackModel
              Required: true
      Policies:
        - Statement:
          - Effect: "Allow"
            Action:
              - "ssm:GetParameter*"
            Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${EnvironmentType}/devPortal*'

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
