version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "devportal-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-fqbwexv2bra6"
s3_prefix = "devportal-test"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "OpenSearchURL=\"<ES_URL here>\" PostgresURL=\"<PG_URL here>\" PostgresCert=\"<CA_CERT here>\""
