extends: spelling
message: "'%s' does not seem to be a recognised word"
# The dictionary directory path appears to be relative to the .vale.ini file
dicpath: .github/vale/dicts
# We want to add our dictionary on top of the default dictionary
append: true
dictionaries:
  - aiven
