name: Index devportal pages

on:
  push:
    branches: [ fix-algolia-index-title-refer ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Index pages to OpenSearch
      run: |
        make index-devportal
      env:
        ES_URL: ${{ secrets.ES_URL }}
    - name: Index pages to Algolia for aiven.io search
      run: |
        make index-algolia
      env:
        ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
        ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
        ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
