name: Linting
on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      uses: errata-ai/vale-action@master
      with:
        files: ["docs"]
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

