name: Linting
on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:

jobs:
  prose:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      # We want support for at least vale v2.15.3
      #uses: errata-ai/vale-action@v1.3.0
      uses: errata-ai/vale-action@master
      with:
        files: '["index.rst", "docs"]'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

