name: Linting
on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:

jobs:
  prose:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      # We want support for at least vale v2.15.3
      # The current release of vale-action, v1.5.0, only provides vale 2.15.2
      # So for the moment we need to use vale-action master, which provides
      # at least vale 2.15.5.
      # When there is a vale-action that provides a version we can use, re-pin
      # this to a specific version of vale-action.
      uses: errata-ai/vale-action@reviewdog
      with:
        version: 2.20.0
        files: '["index.rst", "docs"]'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

