name: Manual Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test changed-files
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      max-parallel: 7
      matrix:
        platform:
          [
            ubuntu-latest,
            ubuntu-22.04,
            windows-latest,
            macos-latest,
            macos-11,
            ubuntu-18.04,
            windows-2022,
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Get Renamed files
        id: renamed-dev
        uses: tj-actions/changed-files@v20
        with:
          files: doc/

      - name: List files
        run: |
          for file in ${{ steps.renamed-dev.outputs.old_new_renamed_files }}; do
            echo $file
          done
