name: "Check Renamed files"
"on":
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request: null

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files in the docs folder
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            docs/**
          include_all_old_new_renamed_files: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_old_new_renamed_files }}; do
            echo "$file was changed"
          done
