name: "Test"
"on":
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request: null
  workflow_dispatch:

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v24

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List renamed files
        run: |
          for file in ${{ steps.changed-files.outputs.renamed_files }}; do
            echo "$file was renamed"
          done

      - name: Run changed-files with glob filtering and all_old_new_renamed_files
        id: changed-files-glob-all-old-new-renamed-files
        uses: ./
        with:
          include_all_old_new_renamed_files: true
          files: |
            docs/*.rst

      - name: Show output
        run: |
          echo '${{ toJSON(steps.changed-files-glob-all-old-new-renamed-files.outputs) }}'
