name: "Check Renamed files"
"on":
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request: null

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files in the docs folder
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            docs/**

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check renamed files
        run: |
          for file in ${{ steps.changed-files.outputs.renamed_files }}; 
          do
            if [ "${file: -4}" == ".rst" ]
              file="$file" | sed -e 's/\.[^.]*$//'
              then
                var="$var $file"
            fi
          done
          echo "renamed files"
          echo $var
          if [ -z "$var" ]
          then
              echo "No *.rst changed files renamed."
          else
              echo "renamed FILES"
              echo $var
          fi
